<?php

namespace CF\CentreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    // Trouve la formation suivant le slug
    public function findFormation($slug)
    {
        $qb = $this->createQueryBuilder('f')
            ->where('f.slug = :slug')
                ->setParameter('slug', $slug)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
